FROM node:24-slim

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# COPY packages/db/.env packages/db/.env
# COPY apps/user-app/.env apps/user-app/.env

RUN npm install

RUN apt-get update -y && apt-get install -y openssl

RUN npm run db:generate

RUN npm run build

CMD ["npm", "run", "start-user-app"]